using System.IO;
using System.Text.Json;
using Jot.Services;
using Jot.Services.Abstractions;
using Jot.Transcription.Ggml;
using Jot.Transcription.Nemotron;

namespace Jot.Cli;

/// <summary>Everything the run needs from disk, resolved once.</summary>
/// <param name="Root">The Jot app-data root that won the probe. <c>tools\ffmpeg.exe</c> hangs off THIS,
/// not <paramref name="DataRoot"/> — a user who moved their data to D: still has ffmpeg on C:.</param>
/// <param name="DataRoot">The effective data folder (the root, or its settings.json DataDirectory).</param>
/// <param name="ModelsParent">Folder the engine's model FOLDER sits in — the locators' explicit-directory
/// ctor takes the leaf, which cannot serve both engines, so the join is ours.</param>
internal sealed record ResolvedPaths(
    string Root, string DataRoot, string ModelsParent, JotSettings Settings, string Origin)
{
    public string Int4Dir => Path.Combine(ModelsParent, NemotronModel.ModelFolder);
    public string Fp16Dir => Path.Combine(ModelsParent, NemotronFp16Model.ModelFolder);
    public string GgufDir => Path.Combine(ModelsParent, NemotronGgufModel.ModelFolder);
    public string VocabularyDir => Path.Combine(DataRoot, JotPaths.VocabularyFolderName);
    public string ToolsDir => Path.Combine(Root, "tools");
}

/// <summary>
/// Finds the app's data root from a process that has NO MSIX package identity. That is the whole problem:
/// <c>JotPaths.AppDataRoot</c> resolves to %LOCALAPPDATA%\Jot here even when the installed app is the
/// Store build whose data lives in %LOCALAPPDATA%\Packages\&lt;PFN&gt;\LocalCache, so the CLI must probe
/// instead of asking.
/// </summary>
internal static class CliPaths
{
    /// <summary>Probe order: the unpackaged root first, then every MSIX container that looks like Jot's.
    /// Package Identity names are GENERATED by Partner Center, so matching on a publisher glob is
    /// fragile — the models folder and a DataDirectory redirect are the identifying evidence.</summary>
    public static IReadOnlyList<string> DefaultRoots(string localAppData)
    {
        var roots = new List<string> { Path.Combine(localAppData, "Jot") };
        try
        {
            foreach (string pkg in Directory.EnumerateDirectories(Path.Combine(localAppData, "Packages")))
            {
                string cache = Path.Combine(pkg, "LocalCache");
                if (HasNemotronFolder(Path.Combine(cache, "models")) || HasRedirect(cache))
                    roots.Add(cache);
            }
        }
        catch
        {
            // No Packages folder, or no permission to list it — the unpackaged root still stands.
        }
        return roots;
    }

    /// <param name="modelDirOverride">--model-dir: the models PARENT, not a model folder.</param>
    /// <param name="dataDirOverride">--data-dir: a Jot data root (models\, Vocabulary\, settings.json).</param>
    public static ResolvedPaths Resolve(
        string? modelDirOverride, string? dataDirOverride, IReadOnlyList<string> roots, string fallbackRoot)
    {
        if (dataDirOverride is not null)
        {
            // An explicit data root IS the data root; a DataDirectory redirect inside it would be a
            // second hop the user did not ask for.
            JotSettings s = ReadOnlySettingsStore.Load(dataDirOverride).Current;
            return new ResolvedPaths(
                dataDirOverride, dataDirOverride,
                modelDirOverride ?? Path.Combine(dataDirOverride, "models"), s, "--data-dir");
        }

        foreach (string root in roots)
        {
            ResolvedPaths? candidate = TryRoot(root, modelDirOverride);
            if (candidate is not null) return candidate;
        }

        // Nothing installed anywhere. With --model-dir the models are found by definition, so this is
        // only about where vocabulary/settings come from; without it the models-present check reports it.
        JotSettings fallbackSettings = ReadOnlySettingsStore.Load(fallbackRoot).Current;
        string dataRoot = DataRootOf(fallbackRoot, fallbackSettings);
        return new ResolvedPaths(
            fallbackRoot, dataRoot, modelDirOverride ?? Path.Combine(dataRoot, "models"),
            fallbackSettings, modelDirOverride is not null ? "--model-dir" : "default");
    }

    // An unreadable root (removed drive after a data move) is skipped, never fatal — probing continues.
    private static ResolvedPaths? TryRoot(string root, string? modelDirOverride)
    {
        try
        {
            JotSettings s = ReadOnlySettingsStore.Load(root).Current;
            string dataRoot = DataRootOf(root, s);
            string modelsParent = modelDirOverride ?? Path.Combine(dataRoot, "models");
            bool installed =
                new NemotronModel(Path.Combine(modelsParent, NemotronModel.ModelFolder)).IsInstalled ||
                new NemotronFp16Model(Path.Combine(modelsParent, NemotronFp16Model.ModelFolder)).IsInstalled ||
                new NemotronGgufModel(Path.Combine(modelsParent, NemotronGgufModel.ModelFolder)).IsInstalled;
            return installed ? new ResolvedPaths(root, dataRoot, modelsParent, s, root) : null;
        }
        catch
        {
            return null;
        }
    }

    private static string DataRootOf(string root, JotSettings s) =>
        string.IsNullOrWhiteSpace(s.DataDirectory) ? root : s.DataDirectory!;

    private static bool HasNemotronFolder(string modelsDir)
    {
        try { return Directory.EnumerateDirectories(modelsDir, "nemotron-*").Any(); }
        catch { return false; }
    }

    private static bool HasRedirect(string root)
    {
        try { return !string.IsNullOrWhiteSpace(ReadOnlySettingsStore.Load(root).Current.DataDirectory); }
        catch { return false; }
    }
}

/// <summary>
/// settings.json, read and never written. <see cref="JsonSettingsStore"/> can't be reused: its Dir and
/// FilePath are static readonly snapshots of <c>JotPaths.ConfigDir</c>, which for this process is always
/// the unpackaged root. Same type, same tolerate-missing/corrupt behavior, no writers.
/// </summary>
internal sealed class ReadOnlySettingsStore : ISettingsStore
{
    private static readonly JsonSerializerOptions Options = new() { WriteIndented = true };

    public JotSettings Current { get; }

    public event EventHandler? Changed { add { } remove { } }

    private ReadOnlySettingsStore(JotSettings settings) => Current = settings;

    public static ReadOnlySettingsStore Load(string root)
    {
        try
        {
            string path = Path.Combine(root, "settings.json");
            if (File.Exists(path) &&
                JsonSerializer.Deserialize<JotSettings>(File.ReadAllText(path), Options) is { } loaded)
                return new ReadOnlySettingsStore(loaded);
        }
        catch
        {
            // Corrupt or unreadable settings fall back to defaults, exactly as the app does.
        }
        return new ReadOnlySettingsStore(new JotSettings());
    }

    public void Save() { }

    public void Reset() { }
}
